campos2 = [
{columna:'cod_circ',indicador:'',dimension:'',eje:''},{columna:'zona',indicador:'',dimension:'',eje:''},{columna:'dpa_provin',indicador:'',dimension:'',eje:''},{columna:'dpa_despro',indicador:'',dimension:'',eje:''},{columna:'dpa_canton',indicador:'',dimension:'',eje:''},{columna:'dpa_descan',indicador:'',dimension:'',eje:''},{columna:'dpa_parroq',indicador:'',dimension:'',eje:''},{columna:'des_circ',indicador:'',dimension:'',eje:''},{columna:'genero_hombres',indicador:'Población Total Hombres',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'genero_mujeres',indicador:'Población Total Mujeres',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'poblacion_total',indicador:'Población Total',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Crecimiento Poblacional',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Total crecimiento Poblacional',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Crecimiento Poblacional por grupo etario',dimension:'Dinámicas Poblacionales',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Dependencia demográfica',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'total_pet',indicador:'PET',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'total_pea',indicador:'PEA',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'total_pei',indicador:'PEI',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'dependencia_tercera_edad_tot_65_mas',indicador:'Relación de dependencia de la tercera edad',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'total_adultos',indicador:'Pablación Adulta Total',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'total_hogares',indicador:'Total Hogares',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'dependencia_demografica_tot_15_64',indicador:'Habitantes Dependientes < 15 Años > 64 Años',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},{columna:'dependencia_demografica_pop_dep',indicador:'Población Dependiente',dimension:'Estructura de la Población',eje:'Dimensión 1: Población y Territorio'},
{columna:'null',indicador:'Área Urbana',dimension:'Área Urbana',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Compacidad',dimension:'Compacidad',eje:'Dimensión 1: Población y Territorio'},{columna:'null',indicador:'Densidad',dimension:'Densidad',eje:'Dimensión 1: Población y Territorio'},{columna:'hogares_internet',indicador:'Acceso a internet',dimension:'Conectividad',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'h_si_compu',indicador:'Hogares con computador',dimension:'Conectividad',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Calidad del acceso vial a la vivienda',dimension:'Equipamientos de cercanía',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Equipamiento comunitario ',dimension:'Equipamientos de cercanía',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Equipamiento protección social',dimension:'Equipamientos de cercanía',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'agua_red_publica',indicador:'Cobertura de agua',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Relación tarifa de agua / salario mínimo',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'viv_alcantarillado',indicador:'Cobertura de alcantarillado',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'luz_electrica_por_red',indicador:'Cobertura de energía eléctrica',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'eliminacion_basura_carro_recolector',indicador:'Recolección domiciliaria de residuos sólidos',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Eliminación de excretas ',dimension:'Servicios Básicos',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Suelo seguro ',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Calidad de la vivienda (Déficit Cualitativo)',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Calidad de la vivienda (Déficit Cuantitativo)',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'tenencia_vivienda',indicador:'Propiedad de la vivienda',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'hacinamiento',indicador:'Hogares en Hacinamiento',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Personas en hogares en hacinamiento',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Producción de vivienda nueva para sectores con menos ingresos',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Regulación de alquiler',dimension:'Suelo y Vivienda',eje:'Dimensión 2: Hábitat, Vivienda y Servicios'},{columna:'null',indicador:'Trabajo Infantil',dimension:'Empleo',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Empleo adecuado',dimension:'Empleo',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Empleo Informal',dimension:'Empleo',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Tasa de Desempleo',dimension:'Empleo',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Coeficiente Gini',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Ingreso Medio de los hogares',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Ingreso promedio por Quintiles',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Ingreso promedio por Grupo etario por sexo',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Brecha salarial por sexo',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Brecha Salarial por sexo y Rama de Actividad',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Cobertura de la Canasta Familiar por Quintiles  por hogar',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Pobreza por consumo',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Pobreza por ingreso',dimension:'Inequidad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_hogares_empleadores',indicador:'Hogares com Empleadores',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Producto Urbano per cápita',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Valor Agregado por Rama ',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Población con educación superior empleada por Rama de Actividad',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Densidad Económica',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Especialización Económica',dimension:'Productividad',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'agricultura_ganaderia_silvicultura_pesca',indicador:'Población en Ganadería o Pesca',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'explotacion_minas_canteras',indicador:'Población en Minas y Canteras',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'industrias_manufactureras',indicador:'Población en Industria Manufacturera ',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'suministro_electricidad_gas_vapor_aire_acondicionado',indicador:'Población en Industría de Energía',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'distribucion_agua_alcantarillado_gestion_deshechos',indicador:'Población en Servicios',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'construccion',indicador:'Población en el Sector de la Contrucción',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'comercio_por_mayor_menor',indicador:'Población en Comercio',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'transporte_almacenamiento',indicador:'Población en Transporte y Almacenamiento',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_alojamiento_servicio_comidas',indicador:'Población en Alojamiento y Restauración',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'informacion_comunicacion',indicador:'Población en Industria de la Comunicación',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_financieras_seguros',indicador:'Población en Actividades Financiera',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_inmobiliarias',indicador:'Población en Actividades Inmobiliarias',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_profesionales_cientificas_tecnicas',indicador:'Población en Actividades Profesionales, Cientificas ',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_servicios_administrativos_apoyo',indicador:'Población en Servicios Administrativos',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'administracion_publica_defensa',indicador:'Población en Defensa Pública',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'ensenanza',indicador:'Población en Enseñanza',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'actividades_atencion_salud_humana',indicador:'Población en Área Salud',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'artes_entretenimiento_recreacion',indicador:'Población en Artes y Recreación',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'otras_actividades_servicios',indicador:'Población en Otras Actividades',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'null',indicador:'Acceso al crédito',dimension:'Sectores Económicos',eje:'Dimensión 3: Capacidad y Potencialidad Productiva'},{columna:'asistencia_basica',indicador:'Tasa de asistencia a programas de primera infancia ',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'asistencia_primaria',indicador:'Tasa de asistencia  educación primaria',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'asistencia_bachillera',indicador:'Tasas de asistencia a bachillerato',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'asistencia_superior',indicador:'Tasa asistencia educación superior',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Contribución de asistencia universitaria',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'analfabetos',indicador:'Tasas de analfabetismo',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Analfabetismo digital',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Asistencia formación continua',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Inscripción equitativa en educación de nivel secundario',dimension:'Educación',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Mujeres en los Gobiernos Locales',dimension:'Equidad de Género',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Mujeres en el Mercado Laboral',dimension:'Equidad de Género',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Reparto modal de la movilidad',dimension:'Movilidad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Proximidad a paradas de transporte público de superficie',dimension:'Movilidad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Tiempo promedio de viaje diario',dimension:'Movilidad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Densidad vial',dimension:'Movilidad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Densidade de las Intersecciones Viales',dimension:'Movilidad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'hogar_nbi',indicador:'NBI',dimension:'Pobreza',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Ingreso ',dimension:'Pobreza',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Multidimensional',dimension:'Pobreza',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Desnutrición infantil',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Tasa de mortalidad materna',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Tasa de mortalidad infantil',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Incidencia de sobrepeso',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Esperanza de vida',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Personal de salud por cada 10.000 ',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Sedentarismo',dimension:'Salud',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Tasa de homicidios ',dimension:'Seguridad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Tasa de Hurtos',dimension:'Seguridad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Fatalidad por Accidentes de Tránsito',dimension:'Seguridad',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'adultos_seguridad_social',indicador:'Trabajadores con seguridad Social',dimension:'Seguridad Social',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Adultos Mayores con Seguridad social',dimension:'Seguridad Social',eje:'Dimensión 4: Pobreza y Acceso a Bienes Públicos'},{columna:'null',indicador:'Concentración de PM10',dimension:'Calidad del Entorno',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Emisiones de CO2',dimension:'Calidad del Entorno',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Áreas Verdes por habitante',dimension:'Calidad del Entorno',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Áreas reforestadas por habitante',dimension:'Calidad del Entorno',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Número de árboles plantados',dimension:'Calidad del Entorno',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Estructura de consumo energético',dimension:'Energía y gestión de recursos',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Autosuficiencia energética de las viviendas',dimension:'Energía y gestión de recursos',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Autosuficiencia hídrica de la demanda urbana (balance hídrico) ',dimension:'Energía y gestión de recursos',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Espacio público',dimension:'Espacio Público',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Oferta de  espacio público',dimension:'Espacio Público',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Reparto de viario público',dimension:'Forma Urbana',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Policentralidad',dimension:'Forma Urbana',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Densidad Vial',dimension:'Forma Urbana',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Superficie Destinada a Vías',dimension:'Forma Urbana',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Reciclaje de Residuos Sólidos',dimension:'Manejo de Residuos',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Recolección selectiva de los residuos sólidos urbanos',dimension:'Manejo de Residuos',eje:'Dimensión 5: Sostenibilidad Urbana'},{columna:'null',indicador:'Índices de acceso a la justicia y de calidad ',dimension:'Calidad institucional local ',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Transparencia y rendición de cuentas la Población',dimension:'Calidad institucional local ',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Políticas de discriminación positiva',dimension:'Capacidad y Calidad Regulatoria',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Días Necesarios para Iniciar un Negocio',dimension:'Capacidad y Calidad Regulatoria',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Planes de regulación de suelo ',dimension:'Capacidad y Calidad Regulatoria',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Eficiencia del Gasto Local',dimension:'Finanzas Municipales y Transparencia',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Recaudación de Ingresos Propios',dimension:'Finanzas Municipales y Transparencia',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Deuda Sub Nacional',dimension:'Finanzas Municipales y Transparencia',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Participación electoral',dimension:'Participación',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Mecanismos de democracia plebiscitaria',dimension:'Participación',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Mecanismos de democracia participativa',dimension:'Participación',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Tejido asociativo ',dimension:'Participación',eje:'Dimensión 6: Gobernanza Urbana'},{columna:'null',indicador:'Existencia de mecanismos de exigibilidad',dimension:'Participación',eje:'Dimensión 6: Gobernanza Urbana'}
]


menu2 = [
{grafico:'null',indicador:'Estructura Productiva',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Evolución de Grandes Infraestructuras',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Evolución Producto Urbano Per Capita',dimension:'Dimensión Económica'},{grafico:'null',indicador:'PEA Urbana por Rama',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Tasa de Desempleo',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Relación Empleo - Población',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Empleo Formal',dimension:'Dimensión Económica'},{grafico:'null',indicador:'Pobreza por NBI',dimension:'Dimensión Social'},{grafico:'null',indicador:'Pobreza Extrema',dimension:'Dimensión Social'},{grafico:'null',indicador:'Ingreso Medio Hogares',dimension:'Dimensión Social'},{grafico:'null',indicador:'Gini',dimension:'Dimensión Social'},{grafico:'null',indicador:'Esperanza de Vida al Nacer',dimension:'Dimensión Social'},{grafico:'null',indicador:'Tasa de Mortalidad en Menores',dimension:'Dimensión Social'},{grafico:'null',indicador:'Cobertura de Vacunación',dimension:'Dimensión Social'},{grafico:'null',indicador:'Mortalidad Materna',dimension:'Dimensión Social'},{grafico:'null',indicador:'Tasa de Alfabetización',dimension:'Dimensión Social'},{grafico:'null',indicador:'Promedio de Años de Escolaridad',dimension:'Dimensión Social'},{grafico:'graf2',indicador:'Tasa de Matriculación',dimension:'Dimensión Social'},{grafico:'null',indicador:'Déficit y Calidad de la Vivienda',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Asentamientos Precarios',dimension:'Dimensión de Hábitat'},{grafico:'graf1',indicador:'Cobertura de Agua',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Saneamiento',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Recolección de Residuos',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Electricidad',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Telecomunicaciones',dimension:'Dimensión de Hábitat'},{grafico:'null',indicador:'Sistema Urbano',dimension:'Dimensión Espacial'},{grafico:'null',indicador:'Indice de Primicia',dimension:'Dimensión Espacial'},{grafico:'null',indicador:'Formación de Regiones Urbanas',dimension:'Dimensión Espacial'},{grafico:'null',indicador:'Morfología Urbana',dimension:'Dimensión Espacial'}
]

agregados = {
graf1 : [
{'ciudad':'CUENCA','Viviendas sin Agua':12.1},
{'ciudad':'GIRON','Viviendas sin Agua':34.6},
{'ciudad':'GUALACEO','Viviendas sin Agua':32.6},
{'ciudad':'NABON','Viviendas sin Agua':40.2},
{'ciudad':'PAUTE','Viviendas sin Agua':41.2},
{'ciudad':'PUCARA','Viviendas sin Agua':54.9},
{'ciudad':'SAN FERNANDO','Viviendas sin Agua':27.7},
{'ciudad':'SANTA ISABEL','Viviendas sin Agua':38.7},
{'ciudad':'SIGSIG','Viviendas sin Agua':49.1},
{'ciudad':'O-1A','Viviendas sin Agua':30.8},
{'ciudad':'CHORDELEG','Viviendas sin Agua':28.4},
{'ciudad':'EL PAN','Viviendas sin Agua':32.1},
{'ciudad':'SEVILLA DE ORO','Viviendas sin Agua':42.2},
{'ciudad':'GUACHAPALA','Viviendas sin Agua':16.8},
{'ciudad':'CAMILO PONCE ENRIQUEZ','Viviendas sin Agua':47.6},
{'ciudad':'GUARANDA','Viviendas sin Agua':39.1},
{'ciudad':'CHILLANES','Viviendas sin Agua':62},
{'ciudad':'SAN JOSE DE CHIMBO','Viviendas sin Agua':43.9},
{'ciudad':'ECHEANDIA','Viviendas sin Agua':36.9},
{'ciudad':'SAN MIGUEL','Viviendas sin Agua':48},
{'ciudad':'CALUMA','Viviendas sin Agua':38.1},
{'ciudad':'LAS NAVES','Viviendas sin Agua':44.7},
{'ciudad':'AZOGUES','Viviendas sin Agua':23.1},
{'ciudad':'BIBLIAN','Viviendas sin Agua':39},
{'ciudad':'CA-1AR','Viviendas sin Agua':41.8},
{'ciudad':'LA TRONCAL','Viviendas sin Agua':32.5},
{'ciudad':'EL TAMBO','Viviendas sin Agua':40.3},
{'ciudad':'DELEG','Viviendas sin Agua':31.7},
{'ciudad':'SUSCAL','Viviendas sin Agua':50.4},
{'ciudad':'TULCAN','Viviendas sin Agua':7.8},
{'ciudad':'BOLIVAR','Viviendas sin Agua':28.3},
{'ciudad':'ESPEJO','Viviendas sin Agua':19.2},
{'ciudad':'MIRA','Viviendas sin Agua':39.1},
{'ciudad':'MONTUFAR','Viviendas sin Agua':12.9},
{'ciudad':'SAN PEDRO DE HUACA','Viviendas sin Agua':6.7},
{'ciudad':'LATACUNGA','Viviendas sin Agua':29.6},
{'ciudad':'LA MANA','Viviendas sin Agua':30.5},
{'ciudad':'PANGUA','Viviendas sin Agua':72.1},
{'ciudad':'PUJILI','Viviendas sin Agua':56},
{'ciudad':'SALCEDO','Viviendas sin Agua':37.3},
{'ciudad':'SAQUISILI','Viviendas sin Agua':46.8},
{'ciudad':'SIGCHOS','Viviendas sin Agua':61.2},
{'ciudad':'RIOBAMBA','Viviendas sin Agua':23.9},
{'ciudad':'ALAUSI','Viviendas sin Agua':54},
{'ciudad':'COLTA','Viviendas sin Agua':58.8},
{'ciudad':'CHAMBO','Viviendas sin Agua':43.4},
{'ciudad':'CHUNCHI','Viviendas sin Agua':42},
{'ciudad':'GUAMOTE','Viviendas sin Agua':54.7},
{'ciudad':'GUANO','Viviendas sin Agua':41.9},
{'ciudad':'PALLATANGA','Viviendas sin Agua':55.2},
{'ciudad':'PENIPE','Viviendas sin Agua':23.4},
{'ciudad':'CUMANDA','Viviendas sin Agua':32.5},
{'ciudad':'MACHALA','Viviendas sin Agua':18.9},
{'ciudad':'ARENILLAS','Viviendas sin Agua':22.2},
{'ciudad':'ATAHUALPA','Viviendas sin Agua':24},
{'ciudad':'BALSAS','Viviendas sin Agua':34.1},
{'ciudad':'CHILLA','Viviendas sin Agua':52.5},
{'ciudad':'EL GUABO','Viviendas sin Agua':32.2},
{'ciudad':'HUAQUILLAS','Viviendas sin Agua':15.6},
{'ciudad':'MARCABELI','Viviendas sin Agua':8.8},
{'ciudad':'PASAJE','Viviendas sin Agua':18.7},
{'ciudad':'PI-1AS','Viviendas sin Agua':24.3},
{'ciudad':'PORTOVELO','Viviendas sin Agua':23.2},
{'ciudad':'SANTA ROSA','Viviendas sin Agua':11.8},
{'ciudad':'ZARUMA','Viviendas sin Agua':38.4},
{'ciudad':'LAS LAJAS','Viviendas sin Agua':21.4},
{'ciudad':'ESMERALDAS','Viviendas sin Agua':12.3},
{'ciudad':'ELOY ALFARO','Viviendas sin Agua':69},
{'ciudad':'MUISNE','Viviendas sin Agua':87},
{'ciudad':'QUININDE','Viviendas sin Agua':68.6},
{'ciudad':'SAN LORENZO','Viviendas sin Agua':35.9},
{'ciudad':'ATACAMES','Viviendas sin Agua':26.2},
{'ciudad':'RIOVERDE','Viviendas sin Agua':79.8},
{'ciudad':'LA CONCORDIA','Viviendas sin Agua':66.1},
{'ciudad':'GUAYAQUIL','Viviendas sin Agua':14.6},
{'ciudad':'ALFREDO BAQUERIZO MORENO','Viviendas sin Agua':68},
{'ciudad':'BALAO','Viviendas sin Agua':44.6},
{'ciudad':'BALZAR','Viviendas sin Agua':65.8},
{'ciudad':'COLIMES','Viviendas sin Agua':67.3},
{'ciudad':'DAULE','Viviendas sin Agua':55.3},
{'ciudad':'DURAN','Viviendas sin Agua':37.2},
{'ciudad':'EL EMPALME','Viviendas sin Agua':66.3},
{'ciudad':'EL TRIUNFO','Viviendas sin Agua':48.6},
{'ciudad':'MILAGRO','Viviendas sin Agua':36.3},
{'ciudad':'NARANJAL','Viviendas sin Agua':43.2},
{'ciudad':'NARANJITO','Viviendas sin Agua':24.4},
{'ciudad':'PALESTINA','Viviendas sin Agua':46.2},
{'ciudad':'PEDRO CARBO','Viviendas sin Agua':76},
{'ciudad':'SAMBORONDON','Viviendas sin Agua':30.3},
{'ciudad':'SANTA LUCIA','Viviendas sin Agua':69.1},
{'ciudad':'URBINA JADO','Viviendas sin Agua':70.5},
{'ciudad':'YAGUACHI','Viviendas sin Agua':46.6},
{'ciudad':'PLAYAS','Viviendas sin Agua':17.4},
{'ciudad':'SIMON BOLIVAR','Viviendas sin Agua':70.1},
{'ciudad':'CORONEL MARCELINO MARIDUE','Viviendas sin Agua':65.2},
{'ciudad':'LOMAS DE SARGENTILLO','Viviendas sin Agua':53.2},
{'ciudad':'NOBOL','Viviendas sin Agua':14.5},
{'ciudad':'GENERAL ANTONIO ELIZALDE','Viviendas sin Agua':36.8},
{'ciudad':'ISIDRO AYORA','Viviendas sin Agua':76.7},
{'ciudad':'IBARRA','Viviendas sin Agua':9.3},
{'ciudad':'ANTONIO ANTE','Viviendas sin Agua':14.9},
{'ciudad':'COTACACHI','Viviendas sin Agua':37.8},
{'ciudad':'OTAVALO','Viviendas sin Agua':27.6},
{'ciudad':'PIMAMPIRO','Viviendas sin Agua':20.6},
{'ciudad':'SAN MIGUEL DE URCUQUI','Viviendas sin Agua':22.3},
{'ciudad':'LOJA','Viviendas sin Agua':16.3},
{'ciudad':'CALVAS','Viviendas sin Agua':33.3},
{'ciudad':'CATAMAYO','Viviendas sin Agua':24},
{'ciudad':'CELICA','Viviendas sin Agua':32.6},
{'ciudad':'CHAGUARPAMBA','Viviendas sin Agua':48.3},
{'ciudad':'ESPINDOLA','Viviendas sin Agua':48.6},
{'ciudad':'GONZANAMA','Viviendas sin Agua':44.8},
{'ciudad':'MACARA','Viviendas sin Agua':31.3},
{'ciudad':'PALTAS','Viviendas sin Agua':46},
{'ciudad':'PUYANGO','Viviendas sin Agua':46.4},
{'ciudad':'SARAGURO','Viviendas sin Agua':47.2},
{'ciudad':'SOZORANGA','Viviendas sin Agua':49.8},
{'ciudad':'ZAPOTILLO','Viviendas sin Agua':55.2},
{'ciudad':'PINDAL','Viviendas sin Agua':51},
{'ciudad':'QUILANGA','Viviendas sin Agua':45.2},
{'ciudad':'OLMEDO','Viviendas sin Agua':53.7},
{'ciudad':'BABAHOYO','Viviendas sin Agua':37},
{'ciudad':'BABA','Viviendas sin Agua':77.3},
{'ciudad':'MONTALVO','Viviendas sin Agua':48.3},
{'ciudad':'PUEBLOVIEJO','Viviendas sin Agua':48.6},
{'ciudad':'QUEVEDO','Viviendas sin Agua':32.6},
{'ciudad':'URDANETA','Viviendas sin Agua':63.3},
{'ciudad':'VENTANAS','Viviendas sin Agua':56.9},
{'ciudad':'VINCES','Viviendas sin Agua':62.3},
{'ciudad':'PALENQUE','Viviendas sin Agua':70.5},
{'ciudad':'BUENA FE','Viviendas sin Agua':28.9},
{'ciudad':'VALENCIA','Viviendas sin Agua':74.9},
{'ciudad':'MOCACHE','Viviendas sin Agua':69.4},
{'ciudad':'QUINSALOMA','Viviendas sin Agua':71.8},
{'ciudad':'PORTOVIEJO','Viviendas sin Agua':37.3},
{'ciudad':'BOLIVAR','Viviendas sin Agua':75.1},
{'ciudad':'CHONE','Viviendas sin Agua':62.1},
{'ciudad':'EL CARMEN','Viviendas sin Agua':51.5},
{'ciudad':'FLAVIO ALFARO','Viviendas sin Agua':83.3},
{'ciudad':'JIPIJAPA','Viviendas sin Agua':41.5},
{'ciudad':'JUNIN','Viviendas sin Agua':63.1},
{'ciudad':'MANTA','Viviendas sin Agua':21.3},
{'ciudad':'MONTECRISTI','Viviendas sin Agua':73.5},
{'ciudad':'PAJAN','Viviendas sin Agua':80.9},
{'ciudad':'PICHINCHA','Viviendas sin Agua':79.7},
{'ciudad':'ROCAFUERTE','Viviendas sin Agua':45.5},
{'ciudad':'SANTA ANA','Viviendas sin Agua':59.2},
{'ciudad':'SUCRE','Viviendas sin Agua':52.7},
{'ciudad':'TOSAGUA','Viviendas sin Agua':36.5},
{'ciudad':'24 DE MAYO','Viviendas sin Agua':76.9},
{'ciudad':'PEDERNALES','Viviendas sin Agua':77},
{'ciudad':'OLMEDO','Viviendas sin Agua':89.2},
{'ciudad':'PUERTO LOPEZ','Viviendas sin Agua':54},
{'ciudad':'JAMA','Viviendas sin Agua':57.2},
{'ciudad':'JARAMIJO','Viviendas sin Agua':24.3},
{'ciudad':'SAN VICENTE','Viviendas sin Agua':47.6},
{'ciudad':'MORONA','Viviendas sin Agua':24.9},
{'ciudad':'GUALAQUIZA','Viviendas sin Agua':40.2},
{'ciudad':'LIMON INDANZA','Viviendas sin Agua':49.3},
{'ciudad':'PALORA','Viviendas sin Agua':26.4},
{'ciudad':'SANTIAGO','Viviendas sin Agua':33.9},
{'ciudad':'SUCUA','Viviendas sin Agua':23.8},
{'ciudad':'HUAMBOYA','Viviendas sin Agua':70.7},
{'ciudad':'SAN JUAN BOSCO','Viviendas sin Agua':49.5},
{'ciudad':'TAISHA','Viviendas sin Agua':90},
{'ciudad':'LOGRO-1O','Viviendas sin Agua':41.3},
{'ciudad':'PABLO VI','Viviendas sin Agua':55.8},
{'ciudad':'TIWINTZA','Viviendas sin Agua':67.2},
{'ciudad':'TENA','Viviendas sin Agua':43.2},
{'ciudad':'ARCHIDONA','Viviendas sin Agua':44.1},
{'ciudad':'EL CHACO','Viviendas sin Agua':20.1},
{'ciudad':'QUIJOS','Viviendas sin Agua':34},
{'ciudad':'CARLOS JULIO AROSEMENA','Viviendas sin Agua':41.8},
{'ciudad':'PASTAZA','Viviendas sin Agua':34.5},
{'ciudad':'MERA','Viviendas sin Agua':25.8},
{'ciudad':'SANTA CLARA','Viviendas sin Agua':44.8},
{'ciudad':'ARAJUNO','Viviendas sin Agua':71.2},
{'ciudad':'QUITO','Viviendas sin Agua':4},
{'ciudad':'CAYAMBE','Viviendas sin Agua':26.2},
{'ciudad':'MEJIA','Viviendas sin Agua':30.6},
{'ciudad':'PEDRO MONCAYO','Viviendas sin Agua':20.1},
{'ciudad':'RUMI-1AHUI','Viviendas sin Agua':6.2},
{'ciudad':'SAN MIGUEL DE LOS BANCOS','Viviendas sin Agua':37.4},
{'ciudad':'PEDRO VICENTE MALDONADO','Viviendas sin Agua':41.4},
{'ciudad':'PUERTO QUITO','Viviendas sin Agua':82.8},
{'ciudad':'AMBATO','Viviendas sin Agua':18.3},
{'ciudad':'BA-1OS','Viviendas sin Agua':17.8},
{'ciudad':'CEVALLOS','Viviendas sin Agua':16.1},
{'ciudad':'MOCHA','Viviendas sin Agua':12.7},
{'ciudad':'PATATE','Viviendas sin Agua':28.6},
{'ciudad':'QUERO','Viviendas sin Agua':35.4},
{'ciudad':'SAN PEDRO DE PELILEO','Viviendas sin Agua':37.6},
{'ciudad':'SANTIAGO DE PILLARO','Viviendas sin Agua':17.6},
{'ciudad':'TISALEO','Viviendas sin Agua':21.3},
{'ciudad':'ZAMORA','Viviendas sin Agua':27.6},
{'ciudad':'CHINCHIPE','Viviendas sin Agua':45.7},
{'ciudad':'NANGARITZA','Viviendas sin Agua':36.2},
{'ciudad':'YACUAMBI','Viviendas sin Agua':59.7},
{'ciudad':'YANTZAZA','Viviendas sin Agua':36.3},
{'ciudad':'EL PANGUI','Viviendas sin Agua':34.4},
{'ciudad':'CENTINELA DEL CONDOR','Viviendas sin Agua':36.2},
{'ciudad':'PALANDA','Viviendas sin Agua':54},
{'ciudad':'PAQUISHA','Viviendas sin Agua':51.7},
{'ciudad':'SAN CRISTOBAL','Viviendas sin Agua':10.1},
{'ciudad':'ISABELA','Viviendas sin Agua':23},
{'ciudad':'SANTA CRUZ','Viviendas sin Agua':19.1},
{'ciudad':'LAGO AGRIO','Viviendas sin Agua':66.3},
{'ciudad':'GONZALO PIZARRO','Viviendas sin Agua':39.6},
{'ciudad':'PUTUMAYO','Viviendas sin Agua':72.5},
{'ciudad':'SHUSHUFINDI','Viviendas sin Agua':48.9},
{'ciudad':'SUCUMBIOS','Viviendas sin Agua':28.6},
{'ciudad':'CASCALES','Viviendas sin Agua':43.2},
{'ciudad':'CUYABENO','Viviendas sin Agua':73.5},
{'ciudad':'ORELLANA','Viviendas sin Agua':42.5},
{'ciudad':'AGUARICO','Viviendas sin Agua':73.4},
{'ciudad':'LA JOYA DE LOS SACHAS','Viviendas sin Agua':58.4},
{'ciudad':'LORETO','Viviendas sin Agua':70.4},
{'ciudad':'SANTO DOMINGO DE LOS TSAC','Viviendas sin Agua':51.1},
{'ciudad':'SANTA ELENA','Viviendas sin Agua':37.4},
{'ciudad':'LIBERTAD','Viviendas sin Agua':12.8},
{'ciudad':'SALINAS','Viviendas sin Agua':11.3},
{'ciudad':'LAS GOLONDRINAS','Viviendas sin Agua':80},
{'ciudad':'MANGA DEL CURA','Viviendas sin Agua':84.2},
{'ciudad':'EL PIEDRERO','Viviendas sin Agua':52.5}
]
,
graf2 : [
{'ciudad':'CUENCA','Pop Edad Escolar':312336},
{'ciudad':'GIRON','Pop Edad Escolar':3819},
{'ciudad':'GUALACEO','Pop Edad Escolar':13123},
{'ciudad':'NABON','Pop Edad Escolar':1174},
{'ciudad':'PAUTE','Pop Edad Escolar':6794},
{'ciudad':'PUCARA','Pop Edad Escolar':874},
{'ciudad':'SAN FERNANDO','Pop Edad Escolar':1393},
{'ciudad':'SANTA ISABEL','Pop Edad Escolar':5286},
{'ciudad':'SIGSIG','Pop Edad Escolar':3473},
{'ciudad':'O-1A','Pop Edad Escolar':798},
{'ciudad':'CHORDELEG','Pop Edad Escolar':3972},
{'ciudad':'EL PAN','Pop Edad Escolar':460},
{'ciudad':'SEVILLA DE ORO','Pop Edad Escolar':781},
{'ciudad':'GUACHAPALA','Pop Edad Escolar':1058},
{'ciudad':'CAMILO PONCE ENRIQUEZ','Pop Edad Escolar':4551},
{'ciudad':'GUARANDA','Pop Edad Escolar':22725},
{'ciudad':'CHILLANES','Pop Edad Escolar':2574},
{'ciudad':'SAN JOSE DE CHIMBO','Pop Edad Escolar':4199},
{'ciudad':'ECHEANDIA','Pop Edad Escolar':5844},
{'ciudad':'SAN MIGUEL','Pop Edad Escolar':6558},
{'ciudad':'CALUMA','Pop Edad Escolar':5934},
{'ciudad':'LAS NAVES','Pop Edad Escolar':1413},
{'ciudad':'AZOGUES','Pop Edad Escolar':32056},
{'ciudad':'BIBLIAN','Pop Edad Escolar':5187},
{'ciudad':'CA-1AR','Pop Edad Escolar':12686},
{'ciudad':'LA TRONCAL','Pop Edad Escolar':32823},
{'ciudad':'EL TAMBO','Pop Edad Escolar':4391},
{'ciudad':'DELEG','Pop Edad Escolar':559},
{'ciudad':'SUSCAL','Pop Edad Escolar':1214},
{'ciudad':'TULCAN','Pop Edad Escolar':50789},
{'ciudad':'BOLIVAR','Pop Edad Escolar':2848},
{'ciudad':'ESPEJO','Pop Edad Escolar':4272},
{'ciudad':'MIRA','Pop Edad Escolar':2982},
{'ciudad':'MONTUFAR','Pop Edad Escolar':13722},
{'ciudad':'SAN PEDRO DE HUACA','Pop Edad Escolar':3660},
{'ciudad':'LATACUNGA','Pop Edad Escolar':60550},
{'ciudad':'LA MANA','Pop Edad Escolar':22137},
{'ciudad':'PANGUA','Pop Edad Escolar':1577},
{'ciudad':'PUJILI','Pop Edad Escolar':9460},
{'ciudad':'SALCEDO','Pop Edad Escolar':11845},
{'ciudad':'SAQUISILI','Pop Edad Escolar':6792},
{'ciudad':'SIGCHOS','Pop Edad Escolar':1813},
{'ciudad':'RIOBAMBA','Pop Edad Escolar':139033},
{'ciudad':'ALAUSI','Pop Edad Escolar':6003},
{'ciudad':'COLTA','Pop Edad Escolar':2213},
{'ciudad':'CHAMBO','Pop Edad Escolar':4233},
{'ciudad':'CHUNCHI','Pop Edad Escolar':3582},
{'ciudad':'GUAMOTE','Pop Edad Escolar':2509},
{'ciudad':'GUANO','Pop Edad Escolar':7373},
{'ciudad':'PALLATANGA','Pop Edad Escolar':3571},
{'ciudad':'PENIPE','Pop Edad Escolar':1001},
{'ciudad':'CUMANDA','Pop Edad Escolar':8059},
{'ciudad':'MACHALA','Pop Edad Escolar':219192},
{'ciudad':'ARENILLAS','Pop Edad Escolar':16431},
{'ciudad':'ATAHUALPA','Pop Edad Escolar':1528},
{'ciudad':'BALSAS','Pop Edad Escolar':3788},
{'ciudad':'CHILLA','Pop Edad Escolar':971},
{'ciudad':'EL GUABO','Pop Edad Escolar':20859},
{'ciudad':'HUAQUILLAS','Pop Edad Escolar':44904},
{'ciudad':'MARCABELI','Pop Edad Escolar':3485},
{'ciudad':'PASAJE','Pop Edad Escolar':49963},
{'ciudad':'PI-1AS','Pop Edad Escolar':14698},
{'ciudad':'PORTOVELO','Pop Edad Escolar':7462},
{'ciudad':'SANTA ROSA','Pop Edad Escolar':46445},
{'ciudad':'ZARUMA','Pop Edad Escolar':9217},
{'ciudad':'LAS LAJAS','Pop Edad Escolar':1132},
{'ciudad':'ESMERALDAS','Pop Edad Escolar':144576},
{'ciudad':'ELOY ALFARO','Pop Edad Escolar':5049},
{'ciudad':'MUISNE','Pop Edad Escolar':5596},
{'ciudad':'QUININDE','Pop Edad Escolar':26994},
{'ciudad':'SAN LORENZO','Pop Edad Escolar':21395},
{'ciudad':'ATACAMES','Pop Edad Escolar':14405},
{'ciudad':'RIOVERDE','Pop Edad Escolar':2905},
{'ciudad':'LA CONCORDIA','Pop Edad Escolar':27056},
{'ciudad':'GUAYAQUIL','Pop Edad Escolar':2153053},
{'ciudad':'ALFREDO BAQUERIZO MORENO','Pop Edad Escolar':7916},
{'ciudad':'BALAO','Pop Edad Escolar':8572},
{'ciudad':'BALZAR','Pop Edad Escolar':26898},
{'ciudad':'COLIMES','Pop Edad Escolar':5778},
{'ciudad':'DAULE','Pop Edad Escolar':61318},
{'ciudad':'DURAN','Pop Edad Escolar':217684},
{'ciudad':'EL EMPALME','Pop Edad Escolar':33349},
{'ciudad':'EL TRIUNFO','Pop Edad Escolar':32649},
{'ciudad':'MILAGRO','Pop Edad Escolar':125856},
{'ciudad':'NARANJAL','Pop Edad Escolar':26699},
{'ciudad':'NARANJITO','Pop Edad Escolar':27004},
{'ciudad':'PALESTINA','Pop Edad Escolar':8005},
{'ciudad':'PEDRO CARBO','Pop Edad Escolar':18896},
{'ciudad':'SAMBORONDON','Pop Edad Escolar':40535},
{'ciudad':'SANTA LUCIA','Pop Edad Escolar':8351},
{'ciudad':'URBINA JADO','Pop Edad Escolar':10080},
{'ciudad':'YAGUACHI','Pop Edad Escolar':16608},
{'ciudad':'PLAYAS','Pop Edad Escolar':31969},
{'ciudad':'SIMON BOLIVAR','Pop Edad Escolar':6886},
{'ciudad':'CORONEL MARCELINO MARIDUE','Pop Edad Escolar':6857},
{'ciudad':'LOMAS DE SARGENTILLO','Pop Edad Escolar':12886},
{'ciudad':'NOBOL','Pop Edad Escolar':7756},
{'ciudad':'GENERAL ANTONIO ELIZALDE','Pop Edad Escolar':5710},
{'ciudad':'ISIDRO AYORA','Pop Edad Escolar':5558},
{'ciudad':'IBARRA','Pop Edad Escolar':125113},
{'ciudad':'ANTONIO ANTE','Pop Edad Escolar':20099},
{'ciudad':'COTACACHI','Pop Edad Escolar':8362},
{'ciudad':'OTAVALO','Pop Edad Escolar':37198},
{'ciudad':'PIMAMPIRO','Pop Edad Escolar':4872},
{'ciudad':'SAN MIGUEL DE URCUQUI','Pop Edad Escolar':3105},
{'ciudad':'LOJA','Pop Edad Escolar':160497},
{'ciudad':'CALVAS','Pop Edad Escolar':12498},
{'ciudad':'CATAMAYO','Pop Edad Escolar':21369},
{'ciudad':'CELICA','Pop Edad Escolar':4123},
{'ciudad':'CHAGUARPAMBA','Pop Edad Escolar':1023},
{'ciudad':'ESPINDOLA','Pop Edad Escolar':1500},
{'ciudad':'GONZANAMA','Pop Edad Escolar':1334},
{'ciudad':'MACARA','Pop Edad Escolar':11918},
{'ciudad':'PALTAS','Pop Edad Escolar':6272},
{'ciudad':'PUYANGO','Pop Edad Escolar':4252},
{'ciudad':'SARAGURO','Pop Edad Escolar':3816},
{'ciudad':'SOZORANGA','Pop Edad Escolar':874},
{'ciudad':'ZAPOTILLO','Pop Edad Escolar':2290},
{'ciudad':'PINDAL','Pop Edad Escolar':1724},
{'ciudad':'QUILANGA','Pop Edad Escolar':836},
{'ciudad':'OLMEDO','Pop Edad Escolar':590},
{'ciudad':'BABAHOYO','Pop Edad Escolar':85359},
{'ciudad':'BABA','Pop Edad Escolar':5021},
{'ciudad':'MONTALVO','Pop Edad Escolar':12032},
{'ciudad':'PUEBLOVIEJO','Pop Edad Escolar':7404},
{'ciudad':'QUEVEDO','Pop Edad Escolar':141851},
{'ciudad':'URDANETA','Pop Edad Escolar':5907},
{'ciudad':'VENTANAS','Pop Edad Escolar':35761},
{'ciudad':'VINCES','Pop Edad Escolar':28459},
{'ciudad':'PALENQUE','Pop Edad Escolar':5965},
{'ciudad':'BUENA FE','Pop Edad Escolar':35729},
{'ciudad':'VALENCIA','Pop Edad Escolar':15917},
{'ciudad':'MOCACHE','Pop Edad Escolar':7567},
{'ciudad':'QUINSALOMA','Pop Edad Escolar':4275},
{'ciudad':'PORTOVIEJO','Pop Edad Escolar':195554},
{'ciudad':'BOLIVAR','Pop Edad Escolar':16712},
{'ciudad':'CHONE','Pop Edad Escolar':50031},
{'ciudad':'EL CARMEN','Pop Edad Escolar':43410},
{'ciudad':'FLAVIO ALFARO','Pop Edad Escolar':5854},
{'ciudad':'JIPIJAPA','Pop Edad Escolar':38027},
{'ciudad':'JUNIN','Pop Edad Escolar':5112},
{'ciudad':'MANTA','Pop Edad Escolar':205073},
{'ciudad':'MONTECRISTI','Pop Edad Escolar':43342},
{'ciudad':'PAJAN','Pop Edad Escolar':6549},
{'ciudad':'PICHINCHA','Pop Edad Escolar':3596},
{'ciudad':'ROCAFUERTE','Pop Edad Escolar':8711},
{'ciudad':'SANTA ANA','Pop Edad Escolar':9185},
{'ciudad':'SUCRE','Pop Edad Escolar':19944},
{'ciudad':'TOSAGUA','Pop Edad Escolar':10194},
{'ciudad':'24 DE MAYO','Pop Edad Escolar':4562},
{'ciudad':'PEDERNALES','Pop Edad Escolar':20429},
{'ciudad':'OLMEDO','Pop Edad Escolar':2004},
{'ciudad':'PUERTO LOPEZ','Pop Edad Escolar':9139},
{'ciudad':'JAMA','Pop Edad Escolar':5719},
{'ciudad':'JARAMIJO','Pop Edad Escolar':15934},
{'ciudad':'SAN VICENTE','Pop Edad Escolar':9297},
{'ciudad':'MORONA','Pop Edad Escolar':17741},
{'ciudad':'GUALAQUIZA','Pop Edad Escolar':6728},
{'ciudad':'LIMON INDANZA','Pop Edad Escolar':3287},
{'ciudad':'PALORA','Pop Edad Escolar':2953},
{'ciudad':'SANTIAGO','Pop Edad Escolar':2151},
{'ciudad':'SUCUA','Pop Edad Escolar':7292},
{'ciudad':'HUAMBOYA','Pop Edad Escolar':840},
{'ciudad':'SAN JUAN BOSCO','Pop Edad Escolar':1313},
{'ciudad':'TAISHA','Pop Edad Escolar':966},
{'ciudad':'LOGRO-1O','Pop Edad Escolar':1385},
{'ciudad':'PABLO VI','Pop Edad Escolar':663},
{'ciudad':'TIWINTZA','Pop Edad Escolar':1089},
{'ciudad':'TENA','Pop Edad Escolar':21892},
{'ciudad':'ARCHIDONA','Pop Edad Escolar':5166},
{'ciudad':'EL CHACO','Pop Edad Escolar':3789},
{'ciudad':'QUIJOS','Pop Edad Escolar':1587},
{'ciudad':'CARLOS JULIO AROSEMENA','Pop Edad Escolar':874},
{'ciudad':'PASTAZA','Pop Edad Escolar':31449},
{'ciudad':'MERA','Pop Edad Escolar':728},
{'ciudad':'SANTA CLARA','Pop Edad Escolar':1247},
{'ciudad':'ARAJUNO','Pop Edad Escolar':1184},
{'ciudad':'QUITO','Pop Edad Escolar':1523735},
{'ciudad':'CAYAMBE','Pop Edad Escolar':36689},
{'ciudad':'MEJIA','Pop Edad Escolar':15583},
{'ciudad':'PEDRO MONCAYO','Pop Edad Escolar':9340},
{'ciudad':'RUMI-1AHUI','Pop Edad Escolar':71443},
{'ciudad':'SAN MIGUEL DE LOS BANCOS','Pop Edad Escolar':4481},
{'ciudad':'PEDRO VICENTE MALDONADO','Pop Edad Escolar':5199},
{'ciudad':'PUERTO QUITO','Pop Edad Escolar':2890},
{'ciudad':'AMBATO','Pop Edad Escolar':157055},
{'ciudad':'BA-1OS','Pop Edad Escolar':12395},
{'ciudad':'CEVALLOS','Pop Edad Escolar':2387},
{'ciudad':'MOCHA','Pop Edad Escolar':1150},
{'ciudad':'PATATE','Pop Edad Escolar':2065},
{'ciudad':'QUERO','Pop Edad Escolar':2572},
{'ciudad':'SAN PEDRO DE PELILEO','Pop Edad Escolar':9580},
{'ciudad':'SANTIAGO DE PILLARO','Pop Edad Escolar':7072},
{'ciudad':'TISALEO','Pop Edad Escolar':1206},
{'ciudad':'ZAMORA','Pop Edad Escolar':11707},
{'ciudad':'CHINCHIPE','Pop Edad Escolar':2977},
{'ciudad':'NANGARITZA','Pop Edad Escolar':1648},
{'ciudad':'YACUAMBI','Pop Edad Escolar':1234},
{'ciudad':'YANTZAZA','Pop Edad Escolar':8563},
{'ciudad':'EL PANGUI','Pop Edad Escolar':2892},
{'ciudad':'CENTINELA DEL CONDOR','Pop Edad Escolar':2092},
{'ciudad':'PALANDA','Pop Edad Escolar':1866},
{'ciudad':'PAQUISHA','Pop Edad Escolar':921},
{'ciudad':'SAN CRISTOBAL','Pop Edad Escolar':6349},
{'ciudad':'ISABELA','Pop Edad Escolar':1962},
{'ciudad':'SANTA CRUZ','Pop Edad Escolar':11379},
{'ciudad':'LAGO AGRIO','Pop Edad Escolar':45502},
{'ciudad':'GONZALO PIZARRO','Pop Edad Escolar':1888},
{'ciudad':'PUTUMAYO','Pop Edad Escolar':2015},
{'ciudad':'SHUSHUFINDI','Pop Edad Escolar':15368},
{'ciudad':'SUCUMBIOS','Pop Edad Escolar':508},
{'ciudad':'CASCALES','Pop Edad Escolar':1930},
{'ciudad':'CUYABENO','Pop Edad Escolar':1169},
{'ciudad':'ORELLANA','Pop Edad Escolar':37688},
{'ciudad':'AGUARICO','Pop Edad Escolar':423},
{'ciudad':'LA JOYA DE LOS SACHAS','Pop Edad Escolar':10722},
{'ciudad':'LORETO','Pop Edad Escolar':3024},
{'ciudad':'SANTO DOMINGO DE LOS TSAC','Pop Edad Escolar':253503},
{'ciudad':'SANTA ELENA','Pop Edad Escolar':36931},
{'ciudad':'LIBERTAD','Pop Edad Escolar':89163},
{'ciudad':'SALINAS','Pop Edad Escolar':32667}

]
};

   	var dimensiones = {};
   	var columnas = {};
   	var ejes = {};
   	
	  		for( var i=0; i<campos2.length; i++ ){
	  				columnas[campos2[i]["columna"]] = campos2[i];
	  				if (campos2[i]["dimension"] != "") {
	  					if(!dimensiones[campos2[i]["dimension"]]){dimensiones[campos2[i]["dimension"]]=[];}	  			
	  					dimensiones[campos2[i]["dimension"]].push( campos2[i] );

						if(!ejes[campos2[i]["eje"]]){ejes[campos2[i]["eje"]]=[];}	
						if(!ejes[campos2[i]["eje"]][campos2[i]["dimension"]]   ){ejes[campos2[i]["eje"]][campos2[i]["dimension"]] =[];}		  					
	  					ejes[campos2[i]["eje"]] [campos2[i]["dimension"]] . push( campos2[i] );
	  				}
	  					  				
	  			}
	  		
	  			  			
     
	  
	  var dimensiones2 = {};
   	var columnas2 = {};
   	var ejes2 = {};
   	
	  		for( var i=0; i<menu2.length; i++ ){
	  				columnas2[menu2[i]["columna"]] = menu2[i];
	  				if (menu2[i]["dimension"] != "") {
	  					if(!dimensiones2[menu2[i]["dimension"]]){dimensiones2[menu2[i]["dimension"]]=[];}	  			
	  					dimensiones2[menu2[i]["dimension"]].push( menu2[i] );

						if(!ejes2[menu2[i]["eje"]]){ejes2[menu2[i]["eje"]]=[];}	
						if(!ejes2[menu2[i]["eje"]][menu2[i]["dimension"]]   ){ejes2[menu2[i]["eje"]][menu2[i]["dimension"]] =[];}		  					
	  					ejes2[menu2[i]["eje"]] [menu2[i]["dimension"]] . push( menu2[i] );
	  				}
	  					  				
	  			}
	  			
	  	
