-- View: mapas.v_circuitos7

-- DROP VIEW mapas.v_circuitos7;

CREATE OR REPLACE VIEW mapas.v_circuitos7 AS 
 SELECT circuitos7.cod_circ,
    circuitos7.zona,
    circuitos7.dpa_provin,
    circuitos7.dpa_despro,
    circuitos7.dpa_canton,
    circuitos7.dpa_descan,
    circuitos7.dpa_parroq,
    circuitos7.des_circ,
    circuitos7.acceso_viviendas,
    circuitos7.total_vivendas,
    circuitos7.adultos_seguridad_social,
    circuitos7.total_adultos,
    circuitos7.analfabetos,
    circuitos7.agua_red_publica_en_vivienda,
    circuitos7.agua_red_publica,
    circuitos7.servicio_higienico_conectado_a_red_publica,
    circuitos7.luz_electrica_por_red,
    circuitos7.eliminacion_basura_carro_recolector,
    circuitos7.hogares_internet,
    circuitos7.hogares_sin_telefono_fijo,
    circuitos7.hogares_con_telefono_fijo,
    circuitos7.total_hogares,
    circuitos7.deficit_habitat_cualitativo,
    circuitos7.deficit_habitat_cuantitativo,
    circuitos7.dependencia_demografica_tot_15_64,
    circuitos7.dependencia_demografica_pop_dep,
    circuitos7.dependencia_tercera_edad_tot_65_mas,
    circuitos7.dependencia_tercera_edad_tot_15_64,
    circuitos7.hacinamiento,
    circuitos7.ge_menor_1,
    circuitos7.ge_1_4,
    circuitos7.ge_5_9,
    circuitos7.ge_10_14,
    circuitos7.ge_15_19,
    circuitos7.ge_20_24,
    circuitos7.ge_25_29,
    circuitos7.ge_30_34,
    circuitos7.ge_35_39,
    circuitos7.ge_40_44,
    circuitos7.ge_45_49,
    circuitos7.ge_50_54,
    circuitos7.ge_55_59,
    circuitos7.ge_60_64,
    circuitos7.ge_65_69,
    circuitos7.ge_70_74,
    circuitos7.ge_75_79,
    circuitos7.ge_80_84,
    circuitos7.ge_85_89,
    circuitos7.ge_90_94,
    circuitos7.ge_95_99,
    circuitos7.ge_mayor_100,
    circuitos7.h_si_compu,
    circuitos7.h_no_compu,
    circuitos7.og_total_hombres,
    circuitos7.og_total_mujeres,
    circuitos7.og_total_poblacion,
    circuitos7.total_pea,
    circuitos7.agricultura_ganaderia_silvicultura_pesca,
    circuitos7.explotacion_minas_canteras,
    circuitos7.industrias_manufactureras,
    circuitos7.suministro_electricidad_gas_vapor_aire_acondicionado,
    circuitos7.distribucion_agua_alcantarillado_gestion_deshechos,
    circuitos7.construccion,
    circuitos7.comercio_por_mayor_menor,
    circuitos7.transporte_almacenamiento,
    circuitos7.actividades_alojamiento_servicio_comidas,
    circuitos7.informacion_comunicacion,
    circuitos7.actividades_financieras_seguros,
    circuitos7.actividades_inmobiliarias,
    circuitos7.actividades_profesionales_cientificas_tecnicas,
    circuitos7.actividades_servicios_administrativos_apoyo,
    circuitos7.administracion_publica_defensa,
    circuitos7.ensenanza,
    circuitos7.actividades_atencion_salud_humana,
    circuitos7.artes_entretenimiento_recreacion,
    circuitos7.otras_actividades_servicios,
    circuitos7.actividades_hogares_empleadores,
    circuitos7.actividades_organizaciones_organos_extraterritoriales,
    circuitos7.no_declarado,
    circuitos7.trabajador_nuevo,
    circuitos7.total_pei,
    circuitos7.total_pet,
    circuitos7.genero_hombres,
    circuitos7.genero_mujeres,
    circuitos7.poblacion_total,
    circuitos7.hogar_nbi,
    circuitos7.asistencia_basica,
    circuitos7.asistencia_primaria,
    circuitos7.asistencia_secundaria,
    circuitos7.asistencia_bachillera,
    circuitos7.asistencia_superior,
    circuitos7.tenencia_vivienda,
    circuitos7.viv_alcantarillado,
    circuitos7.viv_septico,
    st_pointonsurface(circuitos7.geom) AS geometry
   FROM mapas.circuitos7;

ALTER TABLE mapas.v_circuitos7
  OWNER TO indurb;

